forgejo:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: "master"

  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    annotations:
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: forgejo.mabecenter.org  # El dominio donde se accederá a Forgejo
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert  # Certificado TLS para la conexión segura
        hosts:
          - forgejo.mabecenter.org

  gitea:
    admin:
      username: 'workwithdante'
      password: 'Nunc40lv1d4r'
      email: 'dantedevenir@outlook.com'
