forgejo:
  replicaCount: 1
  image:
    registry: code.forgejo.org
    repository: forgejo/forgejo
    tag: 1.20.2-0
  nodeSelector:
    kubernetes.io/hostname: "master"

  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    annotations:
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: forgejo.mabecenter.org  # El dominio donde se accederá a Forgejo
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert  # Certificado TLS para la conexión segura
        hosts:
          - forgejo.mabecenter.org
