forgejo:
  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    annotations:
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: forgejo.mabecenter.org  # El dominio donde se accederá a Forgejo
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert  # Certificado TLS para la conexión segura
        hosts:
          - forgejo.mabecenter.org

  gitea:
    admin:
      existingSecret: gitea-admin-secret
