forgejo-runner:
  runner:
    config:
      create: true
      instance: https://forgejo.mabecenter.org
      name: runner-mabecenter
      token: vQqKi6TdDIREAnQlkRw8h4einrrR5Py9z8zmqkDb
      file:
        log:
          level: "info"
        runner:
          file: ".runner"
          capacity: 1
        envs:
          A_TEST_ENV_NAME_1: null
          A_TEST_ENV_NAME_2: null
          DOCKER_HOST: tcp://127.0.0.1:2376
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: /certs/client
      container:
        network: host
        enable_ipv6: false
        privileged: false
        options: -v /certs/client:/certs/client
        valid_volumes:
          - /certs/client